# Site settings
title: Harrison Solutions
description: A technology solutions company based in Alabama.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "harrisonsolutions.us" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Harrison Solutions
user_description: Harrison Solutions is a technology solutions company based in Alabama. We can work with you on all of your technical needs; <b>no task is too scary nor too difficult</b>.
user_title: Trusted IT Services
email: contact@harrisonsolutions.us
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
